# Generated by Django 3.1.5 on 2021-11-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorymodel',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelTable(
            name='kategorymodel',
            table='Kategori',
        ),
    ]
