# Generated by Django 3.1.5 on 2021-11-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilarmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazilarmodel',
            options={'verbose_name': 'Yazi', 'verbose_name_plural': 'Yazilar'},
        ),
    ]
