# Generated by Django 3.1.5 on 2021-11-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211104_0611'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yazilarmodel',
            table='Yazi',
        ),
    ]
